version: '3.8'

services:
  task_server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "2111:2111"
    networks:
      main_net:
        ipv4_address: 192.20.0.5
    volumes:
      - ./server/customer_events.log:/server/customer_events.log
      - ./server/airddm.db:/server/airddm.db
    command: ["python", "main.py"]

  dispatcher:
    build:
      context: ./dispatcher
      dockerfile: Dockerfile
    ports:
      - "8000:8000"   
    depends_on:
      - task_server
    networks:
      - main_net
    command: ["python", "main.py"]


networks:
  main_net:
    ipam:
      config: 
        - subnet: 192.20.0.0/24